# Generated by Django 3.1.5 on 2021-01-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='OX_easy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OX_hard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OX_normal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test_easy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test_hard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test_normal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('answer', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Multiple',
            new_name='Multiple_easy',
        ),
        migrations.RenameModel(
            old_name='Test',
            new_name='Multiple_hard',
        ),
        migrations.RenameModel(
            old_name='OX',
            new_name='Multiple_normal',
        ),
    ]
