# Generated by Django 3.1.5 on 2021-01-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210126_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Safety_easy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Safety_hard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Safety_normal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service_easy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service_hard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service_normal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transit_easy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transit_hard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transit_normal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('answer', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Multiple_hard',
            new_name='Challenge',
        ),
        migrations.RenameModel(
            old_name='Test_normal',
            new_name='Law_easy',
        ),
        migrations.RenameModel(
            old_name='Test_easy',
            new_name='Law_hard',
        ),
        migrations.RenameModel(
            old_name='OX_normal',
            new_name='Law_normal',
        ),
        migrations.RenameModel(
            old_name='Test_hard',
            new_name='OX_law',
        ),
        migrations.RenameModel(
            old_name='OX_easy',
            new_name='OX_safety',
        ),
        migrations.RenameModel(
            old_name='Multiple_easy',
            new_name='OX_service',
        ),
        migrations.RenameModel(
            old_name='OX_hard',
            new_name='OX_transit',
        ),
        migrations.RenameModel(
            old_name='Multiple_normal',
            new_name='Practice',
        ),
    ]
